name: MOOV
description: A game changing app.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  algolia: ^1.0.1
  animated_check: ^1.0.0
  animated_text_kit: ^4.2.1
  animated_widgets: ^1.0.6
  animations: ^1.1.2
  another_flushbar: ^1.10.8
  auto_size_text: ^2.1.0
  cached_network_image: ^2.2.0+1
  carousel_slider: ^2.3.1
  cloud_firestore: ^2.2.0
  cloud_functions: ^1.1.0
  contacts_service: ^0.4.6
  cupertino_icons: ^0.1.3
  currency_text_input_formatter: ^1.0.3
  date_range_picker: ^1.0.7
  datetime_picker_formfield: ^1.0.0
  draggable_scrollbar: ^0.1.0
  duration: ^2.0.0
  expandable: ^5.0.1
  firebase_analytics: ^8.1.0
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  firebase_core_platform_interface: ^4.0.1
  firebase_messaging: ^10.0.0
  firebase_storage: ^8.1.0
  flutter_app_badger: ^1.1.2
  flutter_bounce: ^1.0.8
  flutter_braintree: ^1.2.1
  flutter_chat_bubble: ^1.0.2
  flutter_device_type: ^0.4.0
  flutter_easyrefresh: ^2.1.8
  flutter_form_builder: ^6.0.1
  flutter_linkify: ^5.0.0
  flutter_reaction_button: ^1.0.7+3
  flutter_screenutil: ^4.0.0
  flutter_sms: ^2.0.0
  flutter_svg: ^0.22.0
  focused_menu: ^1.0.2
  geocoding: ^2.0.0
  geolocator: ^7.0.3
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.0.5
  google_sign_in: ^4.4.4
  http: ^0.13.0
  image: ^3.0.2
  image_cropper: ^1.2.3
  image_picker: ^0.7.5+2
  intl: ^0.17.0
  like_button: ^1.0.4
  list_tile_more_customizable: ^1.3.3
  maps_launcher: ^2.0.0
  material_segmented_control: ^2.1.0
  modal_progress_hud: ^0.1.3
  overlay_support: ^1.2.0
  page_transition: ^1.1.6
  path_provider: ^2.0.1
  permission_handler: ^8.0.0+1
  photo_view: ^0.11.1
  polls: ^0.2.2
  provider: ^4.3.2
  random_string: ^2.1.0
  share: ^0.6.5+4
  shared_preferences: ^0.5.0
  shimmer: ^1.1.2
  splashscreen: ^1.3.5
  swipedetector: ^1.2.0
  syncfusion_flutter_charts: ^18.4.33
  syncfusion_flutter_maps: ^18.4.30-beta
  timeago: ^2.0.17
  url_launcher: ^6.0.4
  worm_indicator: ^0.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/appicon.png
    - lib/assets/google.png
    - lib/assets/moovheader.png
    - lib/assets/foodbutton1.png
    - lib/assets/blockedOverlay.jpg
    - lib/assets/motd.jpg
    - lib/assets/bouts.jpg
    - lib/assets/pete!!.jpg
    - lib/assets/filmbutton1.png
    - lib/assets/sportbutton1.png
    - lib/assets/partybutton1.png
    - lib/assets/otherbutton1.png
    - lib/assets/dummyqr.png
    - lib/assets/ndlogo.png
    - lib/assets/tux.jpg
    - lib/assets/ndlogo1.png
    # - lib/assets/header.jpg
    # - lib/assets/headerNoWhite.jpg
    - lib/assets/kilwins.jpg
    - lib/assets/chens.jpg
    - lib/assets/woman.jpg
    - lib/assets/chinese.png
    - lib/assets/studybutton1.png
    - lib/assets/govbutton1.png
    - lib/assets/massbutton1.png
    - lib/assets/dorm1.png
    - lib/assets/rec.png
    - lib/assets/charitybutton1.png
    - lib/assets/clouds.jpeg
    - lib/assets/tailgatebutton1.png
    - lib/assets/gamesbutton1.png
    - lib/assets/otherbutton2.png
    - lib/assets/me.jpg
    - lib/assets/incognitoCircle.png
    - lib/assets/incognito.png
    - lib/assets/friendfinder.png
    - lib/assets/clubDash.jpeg
    - lib/assets/alvin.png
    - lib/assets/food5.png
    - lib/assets/party2.png
    - lib/assets/club2.png
    - lib/assets/bag1.png
    - lib/assets/fg1.png
    - lib/assets/clubMeeting.gif
    - lib/assets/ff.png
    - lib/assets/egg.png
    - lib/assets/moovblue.png
    - lib/assets/sendmoov.png
    - lib/assets/launchscreen1.png
    - lib/assets/landingpage.png
    - lib/assets/fg.jpeg
    - lib/assets/ratioChart.png
    - lib/assets/moovlogo2.png
    - lib/assets/editclub.jpeg
    - lib/assets/fire.png
    - lib/assets/incognitoPic.jpg
    - lib/assets/welcomePage.png
    - lib/assets/betaWelcome.png
    - lib/assets/moovmoney2.jpg
    - lib/assets/moovmoney.png
    - lib/assets/mapIcon.png
    - lib/assets/mapIconWhite.png
    - lib/assets/betaDisclaimer.png
    - lib/assets/friendsIcon.png
    - lib/assets/friendsIconWhite.png
    - lib/assets/plate.png
    - lib/assets/dance.png
    - lib/assets/recruit.jpeg
    - lib/assets/colorGrid.png
    - lib/assets/trophy.png
    - lib/assets/trophy2.png
    - lib/assets/lead.png
    - lib/assets/verif.png
    - lib/assets/verif2.png
    - lib/assets/music1.png
    - lib/assets/bm1.png
    - lib/assets/virtual1.png
    - lib/assets/placeholderparty1.jpg
    - lib/assets/placeholderparty2.jpg
    - lib/assets/placeholderparty3.jpg
    - lib/assets/placeholderparty0.jpg
    - lib/assets/placeholderbar1.jpg
    - lib/assets/placeholderbar2.jpg
    - lib/assets/placeholderbar3.jpg
    - lib/assets/placeholderbar0.jpg
    - lib/assets/placeholderfood1.jpg
    - lib/assets/placeholderfood2.jpg
    - lib/assets/placeholderfood3.jpg
    - lib/assets/placeholderfood0.jpg
    - lib/assets/random.jpg
    - lib/assets/show3.png
    - lib/assets/clemson.HEIC
    - lib/assets/venmo-icon.png
    - lib/assets/suggestion.png
    - lib/assets/middleFinger.gif
    - lib/assets/icons/BarICON.png
    - lib/assets/icons/BarICON2.png
    - lib/assets/icons/ClubICON.png
    - lib/assets/icons/ClubICON2.png
    - lib/assets/icons/PartyICON.png
    - lib/assets/icons/PartyICON2.png
    - lib/assets/icons/SportICON.png
    - lib/assets/icons/SportICON2.png
    - lib/assets/icons/HangoutsICON.png
    - lib/assets/icons/HangoutsICON2.png

    - lib/assets/icons/RecICON.png
    - lib/assets/icons/RecICON2.png
    - lib/assets/icons/ShowICON.png
    - lib/assets/icons/ShowICON2.png
    - lib/assets/icons/VirtualICON.png
    - lib/assets/icons/VirtualICON2.png
    - lib/assets/badges/10friends.png
    - lib/assets/badges/clink.png
    - lib/assets/badges/natty.png
    - lib/assets/badges/moovMaker.png
    - lib/assets/badges/mountain.png
    - lib/assets/poll.png
    - lib/assets/greenmountain.png
    - lib/assets/sausage.png
    - lib/assets/nd.png
    - lib/assets/runningGif.gif
    - lib/assets/ndMap.json
    # - lib/assets/google1.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Pacifico
  #     fonts:
  #       - asset: assets/Pacifico-Regular.ttf
fonts:
  - family: Solway
    fonts:
      - asset: lib/assets/fonts/Solway-Regular.ttf
      - asset: lib/assets/fonts/Solway-Bold.ttf
        weight: 700
        style: italic

  - family: OpenSans-Bold
    fonts:
      - asset: lib/assets/fonts/OpenSans-Bold.ttf
    # - family: Solway
    #   fonts:
    #     - asset: lib/fonts/So.ttf
    #     - asset: lib/fonts/TrajanPro_Bold.ttf
    #       weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
